@startuml
skinparam classAttributeIconSize 0

package Modules {}

package core {
}

package "psOff Emulator" {

}

Modules -> core

core <-- "psOff Emulator"
core --> "psOff Emulator" : callbacks

@enduml