#pragma once
#include <stdint.h>

namespace Err {

constexpr int32_t NOT_OPENED          = -2144993279;
constexpr int32_t BUSY                = -2144993278;
constexpr int32_t INVALID_PORT        = -2144993277;
constexpr int32_t INVALID_POINTER     = -2144993276;
constexpr int32_t PORT_FULL           = -2144993275;
constexpr int32_t INVALID_SIZE        = -2144993274;
constexpr int32_t INVALID_FORMAT      = -2144993273;
constexpr int32_t INVALID_SAMPLE_FREQ = -2144993272;
constexpr int32_t INVALID_VOLUME      = -2144993271;
constexpr int32_t INVALID_PORT_TYPE   = -2144993270;
constexpr int32_t INVALID_CONF_TYPE   = -2144993268;
constexpr int32_t OUT_OF_MEMORY       = -2144993267;
constexpr int32_t ALREADY_INIT        = -2144993266;
constexpr int32_t NOT_INIT            = -2144993265;
constexpr int32_t MEMORY              = -2144993264;
constexpr int32_t SYSTEM_RESOURCE     = -2144993263;
constexpr int32_t TRANS_EVENT         = -2144993262;
constexpr int32_t INVALID_FLAG        = -2144993261;
constexpr int32_t INVALID_MIXLEVEL    = -2144993260;
constexpr int32_t INVALID_ARG         = -2144993259;
constexpr int32_t INVALID_PARAM       = -2144993258;
} // namespace Err

constexpr int        PORT_OUT_MAX = 6;
static constexpr int PORT_IN_MAX  = 8;

#define SCE_AUDIO_MIN_LEN                256u
#define SCE_AUDIO_MAX_LEN                (256u * 8)
#define SCE_AUDIO_OUT_PARAM_FORMAT_MASK  (0x000000FF)
#define SCE_AUDIO_OUT_PARAM_FORMAT_SHIFT (0)

// sceAudioOutOpen()の引数 paramのattributeの値とマスク値
#define SCE_AUDIO_OUT_PARAM_ATTR_RESTRICTED  (0x00010000)
#define SCE_AUDIO_OUT_PARAM_ATTR_MIX_TO_MAIN (0x00020000)

#define SCE_AUDIO_OUT_PARAM_ATTR_MASK  (0x000F0000)
#define SCE_AUDIO_OUT_PARAM_ATTR_SHIFT (16)

#define SCE_AUDIO_VOLUME_SHIFT     15
#define SCE_AUDIO_OUT_VOLUME_SHIFT SCE_AUDIO_VOLUME_SHIFT
#define SCE_AUDIO_VOLUME_0DB       (1 << SCE_AUDIO_VOLUME_SHIFT)
#define SCE_AUDIO_VOLUME_0dB       SCE_AUDIO_VOLUME_0DB
#define SCE_AUDIO_OUT_VOLUME_0DB   SCE_AUDIO_VOLUME_0DB
#define SCE_AUDIO_OUT_VOLUME_0dB   SCE_AUDIO_VOLUME_0dB

/*J 引数 'flag' に設定する値 */
/*E Value set for the argument 'flag' */
#define SCE_AUDIO_VOLUME_FLAG_L_CH      (1 << 0)
#define SCE_AUDIO_VOLUME_FLAG_FL_CH     SCE_AUDIO_VOLUME_FLAG_L_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_L_CH  SCE_AUDIO_VOLUME_FLAG_L_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_FL_CH SCE_AUDIO_VOLUME_FLAG_L_CH

#define SCE_AUDIO_VOLUME_FLAG_R_CH      (1 << 1)
#define SCE_AUDIO_VOLUME_FLAG_FR_CH     SCE_AUDIO_VOLUME_FLAG_R_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_R_CH  SCE_AUDIO_VOLUME_FLAG_R_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_FR_CH SCE_AUDIO_VOLUME_FLAG_R_CH

#define SCE_AUDIO_VOLUME_FLAG_C_CH       (1 << 2)
#define SCE_AUDIO_VOLUME_FLAG_FC_CH      SCE_AUDIO_VOLUME_FLAG_C_CH
#define SCE_AUDIO_VOLUME_FLAG_CNT_CH     SCE_AUDIO_VOLUME_FLAG_C_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_C_CH   SCE_AUDIO_VOLUME_FLAG_C_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_FC_CH  SCE_AUDIO_VOLUME_FLAG_C_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_CNT_CH SCE_AUDIO_VOLUME_FLAG_C_CH

#define SCE_AUDIO_VOLUME_FLAG_LFE_CH     (1 << 3)
#define SCE_AUDIO_OUT_VOLUME_FLAG_LFE_CH SCE_AUDIO_VOLUME_FLAG_LFE_CH

#define SCE_AUDIO_VOLUME_FLAG_LS_CH     (1 << 4)
#define SCE_AUDIO_VOLUME_FLAG_RL_CH     SCE_AUDIO_VOLUME_FLAG_LS_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_LS_CH SCE_AUDIO_VOLUME_FLAG_LS_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_RL_CH SCE_AUDIO_VOLUME_FLAG_LS_CH

#define SCE_AUDIO_VOLUME_FLAG_RS_CH     (1 << 5)
#define SCE_AUDIO_VOLUME_FLAG_RR_CH     SCE_AUDIO_VOLUME_FLAG_RS_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_RS_CH SCE_AUDIO_VOLUME_FLAG_RS_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_RR_CH SCE_AUDIO_VOLUME_FLAG_RS_CH

#define SCE_AUDIO_VOLUME_FLAG_LE_CH     (1 << 6)
#define SCE_AUDIO_VOLUME_FLAG_BL_CH     SCE_AUDIO_VOLUME_FLAG_LE_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_LE_CH SCE_AUDIO_VOLUME_FLAG_LE_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_BL_CH SCE_AUDIO_VOLUME_FLAG_LE_CH

#define SCE_AUDIO_VOLUME_FLAG_RE_CH     (1 << 7)
#define SCE_AUDIO_VOLUME_FLAG_BR_CH     SCE_AUDIO_VOLUME_FLAG_RE_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_RE_CH SCE_AUDIO_VOLUME_FLAG_RE_CH
#define SCE_AUDIO_OUT_VOLUME_FLAG_BR_CH SCE_AUDIO_VOLUME_FLAG_RE_CH

#define SCE_AUDIO_MIXLEVEL_PADSPK_SHIFT     15
#define SCE_AUDIO_OUT_MIXLEVEL_PADSPK_SHIFT SCE_AUDIO_MIXLEVEL_PADSPK_SHIFT
#define SCE_AUDIO_MIXLEVEL_PADSPK_0DB       (1 << SCE_AUDIO_MIXLEVEL_PADSPK_SHIFT)
#define SCE_AUDIO_MIXLEVEL_PADSPK_0dB       SCE_AUDIO_MIXLEVEL_PADSPK_0DB
#define SCE_AUDIO_OUT_MIXLEVEL_PADSPK_0DB   SCE_AUDIO_MIXLEVEL_PADSPK_0DB
#define SCE_AUDIO_OUT_MIXLEVEL_PADSPK_0dB   SCE_AUDIO_MIXLEVEL_PADSPK_0dB

/*J 引数 'mixLevel' に設定する値の初期値 -9dB */
/*E Defult value set for the argument 'mixLevel' -9dB */
#define SCE_AUDIO_OUT_MIXLEVEL_PADSPK_DEFAULT (11626)